export const CATEGORIES_MAP_TYPES = {
  FETCH_CATEGORIES_START: "Categories/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "Categories/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "Categories/FETCH_CATEGORIES_FAILED",
};
